version: '3.8'

services:
  wrapper:
    image: karen-wrapper:local
    privileged: true
    container_name: karen-wrapper
    volumes:
      - ./wrapper/wrapper-data:/app/rootfs/data
    ports:
      - "10020:10020"
      - "20020:20020"
      - "30020:30020"
    environment:
      - args="-H 0.0.0.0"
    restart: unless-stopped

  bot:
    build: ./bot
    container_name: karen-bot
    depends_on:
      - wrapper
    volumes:
      - ./bot/config.yaml:/app/config.yaml
      - ./bot/downloads:/downloads
      - ./bot/telegram-cache.json:/app/telegram-cache.json
    command: ["--bot"]
    restart: unless-stopped
