#!/bin/bash
# Generate bot/config.yaml + docker-compose.override.yml from .env.
# The count of APPLE_ID_N pairs in .env drives how many wrapper-manager
# instances (and gRPC addresses) are produced. Safe to re-run anytime;
# it only rewrites generated files.
set -euo pipefail

KAREN="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$KAREN"

if [[ ! -f .env ]]; then
  echo "ERROR: .env not found. Copy .env.example to .env and fill it in." >&2
  exit 1
fi

# Parse .env literally — do NOT `source` it. Sourcing runs values as shell, so a
# password containing $, backticks or \ would be expanded/mangled (and break
# under `set -u`). Here values are taken verbatim; only matching outer quotes
# are stripped.
load_env() {
  local line key val
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    line="${line#"${line%%[![:space:]]*}"}"   # ltrim
    [[ -z "$line" || "$line" == \#* || "$line" != *=* ]] && continue
    key="${line%%=*}"
    val="${line#*=}"
    key="${key%"${key##*[![:space:]]}"}"       # rtrim key
    case "$val" in
      \"*\") val="${val#\"}"; val="${val%\"}" ;;
      \'*\') val="${val#\'}"; val="${val%\'}" ;;
    esac
    printf -v "$key" '%s' "$val"
    export "${key?}"
  done < .env
}
load_env

# --- Count Apple accounts (sequential APPLE_ID_1..N, no gaps) ---
N=0
while :; do
  next=$((N + 1))
  id_var="APPLE_ID_${next}"
  if [[ -n "${!id_var:-}" ]]; then
    N=$next
  else
    break
  fi
done

if [[ "$N" -eq 0 ]]; then
  echo "ERROR: no APPLE_ID_1 found in .env — need at least one account." >&2
  exit 1
fi
echo "Detected $N Apple account(s) → $N wrapper-manager instance(s)."

# --- Helpers ---
# Convert "a,b, c" into YAML inline array "[a, b, c]" (numbers, unquoted).
csv_to_yaml_array() {
  local raw="${1:-}" out="" item
  IFS=',' read -ra parts <<< "$raw"
  for item in "${parts[@]}"; do
    item="$(echo "$item" | xargs)"   # trim
    [[ -z "$item" ]] && continue
    [[ -n "$out" ]] && out+=", "
    out+="$item"
  done
  echo "[$out]"
}

ALLOWED_IDS_YAML="$(csv_to_yaml_array "${TELEGRAM_ALLOWED_CHAT_IDS:-}")"
ADMIN_IDS_YAML="$(csv_to_yaml_array "${ADMIN_IDS:-}")"

# --- bot/config.yaml ---
# Non-secret values mirror the authoritative production config:
# /downloads/{ALAC,Atmos,AAC}, playlist uses songinfo + own cover.
{
cat <<YAML
# GENERATED by generate.sh from .env — do not edit by hand.
# Change values in .env and re-run ./generate.sh (or ./setup.sh).
media-user-token: "${MEDIA_USER_TOKEN:-}"
authorization-token: "your-authorization-token"
language: ""
lrc-type: "lyrics"
lrc-format: "lrc"
embed-lrc: true
save-lrc-file: false
save-artist-cover: false
save-animated-artwork: false
emby-animated-artwork: false
embed-cover: true
cover-size: 5000x5000
cover-format: jpg
alac-save-folder: "/downloads/ALAC"
atmos-save-folder: "/downloads/Atmos"
aac-save-folder: "/downloads/AAC"
max-memory-limit: 256
aac-type: aac-lc
alac-max: 192000
atmos-max: 2768
limit-max: 200
album-folder-format: "{AlbumName}"
playlist-folder-format: "{PlaylistName}"
song-file-format: "{SongNumer}. {SongName}"
artist-folder-format: "{UrlArtistName}"
explicit-choice: "[E]"
clean-choice: "[C]"
apple-master-choice: "[M]"
use-songinfo-for-playlist: true
dl-albumcover-for-playlist: true
mv-audio-type: aac
mv-max: 1080
storefront: "us"
convert-after-download: false
convert-format: "flac"
convert-keep-original: false
convert-skip-if-source-matches: true
ffmpeg-path: "ffmpeg"
convert-extra-args: ""
convert-warn-lossy-to-lossless: true
convert-skip-lossy-to-lossless: true
telegram-bot-token: "${TELEGRAM_BOT_TOKEN:-}"
telegram-api-url: ""
telegram-allowed-chat-ids: ${ALLOWED_IDS_YAML}
telegram-admin-ids: ${ADMIN_IDS_YAML}
telegram-cache-chat-id: 0
telegram-search-limit: 8
telegram-search-language: ""
telegram-max-file-mb: 50
telegram-download-folder: ""
telegram-cache-file: ""
telegram-download-max-gb: 22
rip-flush-threshold-gb: ${RIP_FLUSH_THRESHOLD_GB:-20}
telegram-request-timeout-seconds: 3600
telegram-api-id: ${TELEGRAM_API_ID:-0}
telegram-api-hash: "${TELEGRAM_API_HASH:-}"
gofile-token: "${GOFILE_TOKEN:-}"
database-url: "${DATABASE_URL:-}"
task-concurrency: true
lend-head-remaining-threshold: 50
borrower-max-tracks: 30
wrapper-manager-addrs:
YAML
for ((i = 1; i <= N; i++)); do
  echo "  - \"karen-wm-${i}:$((8080 + i))\""
done
} > bot/config.yaml
echo "Wrote bot/config.yaml"

# --- docker-compose.override.yml (N wrapper services + volumes) ---
{
echo "# GENERATED by generate.sh from .env — do not edit by hand."
echo "# Merged automatically with docker-compose.yml by Docker Compose."
echo "services:"
for ((i = 1; i <= N; i++)); do
  port=$((8080 + i))
cat <<YAML
  wrapper-manager-${i}:
    build: ./wrapper-manager
    image: karen-wrapper-manager:local
    privileged: true
    container_name: karen-wm-${i}
    ports:
      - "127.0.0.1:${port}:${port}"
    volumes:
      - wm-data-${i}:/root/data
    command: ["--host", "0.0.0.0", "--port", "${port}", "-debug"]
    restart: unless-stopped
YAML
done
echo ""
echo "volumes:"
for ((i = 1; i <= N; i++)); do
  echo "  wm-data-${i}:"
done
} > docker-compose.override.yml
echo "Wrote docker-compose.override.yml"

# Ensure the persistent state DIRECTORY exists before `docker compose up`. The
# bot keeps all mutable JSON here (telegram-cache.json, telegram-state.json,
# telegram-schedule.json) and docker-compose.yml bind-mounts the whole dir, so
# atomic tmp+rename saves actually reach the host (a single-file mount would
# break them — see the comment in docker-compose.yml). Gitignored; empty/missing
# files are treated as "defaults" by the bot on first load.
mkdir -p bot/state
echo "Ensured bot/state/ exists"
