package structs

import "sync"

type ConfigSet struct {
	Storefront                 string  `yaml:"storefront"`
	AuthorizationToken         string  `yaml:"authorization-token"`
	Language                   string  `yaml:"language"`
	SaveLrcFile                bool    `yaml:"save-lrc-file"`
	LrcType                    string  `yaml:"lrc-type"`
	LrcFormat                  string  `yaml:"lrc-format"`
	SaveAnimatedArtwork        bool    `yaml:"save-animated-artwork"`
	EmbyAnimatedArtwork        bool    `yaml:"emby-animated-artwork"`
	EmbedLrc                   bool    `yaml:"embed-lrc"`
	EmbedCover                 bool    `yaml:"embed-cover"`
	SaveArtistCover            bool    `yaml:"save-artist-cover"`
	CoverSize                  string  `yaml:"cover-size"`
	CoverFormat                string  `yaml:"cover-format"`
	AlacSaveFolder             string  `yaml:"alac-save-folder"`
	AtmosSaveFolder            string  `yaml:"atmos-save-folder"`
	AacSaveFolder              string  `yaml:"aac-save-folder"`
	AlbumFolderFormat          string  `yaml:"album-folder-format"`
	PlaylistFolderFormat       string  `yaml:"playlist-folder-format"`
	ArtistFolderFormat         string  `yaml:"artist-folder-format"`
	SongFileFormat             string  `yaml:"song-file-format"`
	ExplicitChoice             string  `yaml:"explicit-choice"`
	CleanChoice                string  `yaml:"clean-choice"`
	AppleMasterChoice          string  `yaml:"apple-master-choice"`
	MaxMemoryLimit             int     `yaml:"max-memory-limit"`
	AacType                    string  `yaml:"aac-type"`
	AlacMax                    int     `yaml:"alac-max"`
	AtmosMax                   int     `yaml:"atmos-max"`
	LimitMax                   int     `yaml:"limit-max"`
	UseSongInfoForPlaylist     bool    `yaml:"use-songinfo-for-playlist"`
	DlAlbumcoverForPlaylist    bool    `yaml:"dl-albumcover-for-playlist"`
	MVAudioType                string  `yaml:"mv-audio-type"`
	MVMax                      int     `yaml:"mv-max"`
	ConvertAfterDownload       bool    `yaml:"convert-after-download"`
	ConvertFormat              string  `yaml:"convert-format"`
	ConvertKeepOriginal        bool    `yaml:"convert-keep-original"`
	ConvertSkipIfSourceMatch   bool    `yaml:"convert-skip-if-source-matches"`
	FFmpegPath                 string  `yaml:"ffmpeg-path"`
	ConvertExtraArgs           string  `yaml:"convert-extra-args"`
	ConvertWarnLossyToLossless bool    `yaml:"convert-warn-lossy-to-lossless"`
	ConvertSkipLossyToLossless bool    `yaml:"convert-skip-lossy-to-lossless"`
	TelegramBotToken           string  `yaml:"telegram-bot-token"`
	TelegramAllowedChatIDs     []int64 `yaml:"telegram-allowed-chat-ids"`
	TelegramAdminIDs           []int64 `yaml:"telegram-admin-ids"`
	TelegramCacheChatID        int64   `yaml:"telegram-cache-chat-id"`
	TelegramSearchLimit        int     `yaml:"telegram-search-limit"`
	TelegramSearchLanguage     string  `yaml:"telegram-search-language"`
	TelegramMaxFileMB          int     `yaml:"telegram-max-file-mb"`
	TelegramDownloadFolder     string  `yaml:"telegram-download-folder"`
	TelegramCacheFile          string  `yaml:"telegram-cache-file"`
	TelegramAPIURL             string  `yaml:"telegram-api-url"`
	TelegramDownloadMaxGB         int `yaml:"telegram-download-max-gb"`
	RipFlushThresholdGB           int `yaml:"rip-flush-threshold-gb"`
	TelegramRequestTimeoutSeconds int `yaml:"telegram-request-timeout-seconds"`
	TelegramApiID                 int    `yaml:"telegram-api-id"`
	TelegramApiHash               string `yaml:"telegram-api-hash"`
	GofileToken                   string  `yaml:"gofile-token"`
	MediaUserToken                string  `yaml:"media-user-token"`
	WrapperManagerAddrs           []string `yaml:"wrapper-manager-addrs"`

	// TaskConcurrency enables running more than one queued rip at a time: a head
	// task downloads with the full wrapper pool while an eligible queued gofile
	// task borrows a few wrappers, and a finished rip's upload runs detached so the
	// next download starts immediately. Off (default) preserves the strictly serial
	// one-task-at-a-time worker.
	TaskConcurrency bool `yaml:"task-concurrency"`
	// LendHeadRemainingThreshold: a borrower may take wrappers only while the head
	// task still has more than this many tracks left to download. Default 50.
	LendHeadRemainingThreshold int `yaml:"lend-head-remaining-threshold"`
	// BorrowerMaxTracks: only a queued gofile task with fewer than this many total
	// tracks is eligible to borrow. Default 30.
	BorrowerMaxTracks int `yaml:"borrower-max-tracks"`
}

type Counter struct {
	mu          sync.Mutex
	Unavailable int
	NotSong     int
	Error       int
	Success     int
	Total       int
}

func (c *Counter) Inc(field *int) {
	c.mu.Lock()
	*field++
	c.mu.Unlock()
}

// 艺术家页面
type AutoGeneratedArtist struct {
	Next string `json:"next"`
	Data []struct {
		ID         string `json:"id"`
		Type       string `json:"type"`
		Href       string `json:"href"`
		Attributes struct {
			Previews []struct {
				URL string `json:"url"`
			} `json:"previews"`
			Artwork struct {
				Width      int    `json:"width"`
				Height     int    `json:"height"`
				URL        string `json:"url"`
				BgColor    string `json:"bgColor"`
				TextColor1 string `json:"textColor1"`
				TextColor2 string `json:"textColor2"`
				TextColor3 string `json:"textColor3"`
				TextColor4 string `json:"textColor4"`
			} `json:"artwork"`
			ArtistName           string   `json:"artistName"`
			URL                  string   `json:"url"`
			DiscNumber           int      `json:"discNumber"`
			GenreNames           []string `json:"genreNames"`
			HasTimeSyncedLyrics  bool     `json:"hasTimeSyncedLyrics"`
			IsMasteredForItunes  bool     `json:"isMasteredForItunes"`
			IsAppleDigitalMaster bool     `json:"isAppleDigitalMaster"`
			ContentRating        string   `json:"contentRating"`
			DurationInMillis     int      `json:"durationInMillis"`
			ReleaseDate          string   `json:"releaseDate"`
			Name                 string   `json:"name"`
			Isrc                 string   `json:"isrc"`
			AudioTraits          []string `json:"audioTraits"`
			HasLyrics            bool     `json:"hasLyrics"`
			AlbumName            string   `json:"albumName"`
			PlayParams           struct {
				ID   string `json:"id"`
				Kind string `json:"kind"`
			} `json:"playParams"`
			TrackNumber  int    `json:"trackNumber"`
			AudioLocale  string `json:"audioLocale"`
			ComposerName string `json:"composerName"`
		} `json:"attributes"`
	} `json:"data"`
}
